#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    result = []
    score_a = 0 
    score_b = 0
    for x,y in zip(a,b):
        if x > y:
            score_a += 1
            score_b += 0
        elif y > x:
            score_a += 0
            score_b += 1
        else:
            score_a += 0
            score_b += 0
    result = [score_a,score_b]
    return result
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
