#!/bin/python3

import math
import os
import random
import re
import sys

def simpleArraySum(ar):
    result=0;
    for index in range(len(ar)):
        result+=ar[index]
    return result
  
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = aVeryBigSum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
